name: Consolidate Batches
description: Simple consolidation of batch review results.

inputs:
  gemini_api_key:
    description: 'Gemini API key for generating summaries'
    required: true
  workspace:
    description: 'The workspace directory where artifacts are downloaded'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Gemini CLI
      shell: bash
      run: |
        set -euo pipefail
        for i in 1 2 3; do
          if npm install -g @google/gemini-cli; then exit 0; fi
          echo "npm install failed, retrying ($((3-i)) left)"; sleep 5
        done
        exit 1

    - shell: bash
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
      run: |
        set -euo pipefail
        
        cd ${{ inputs.workspace }}
        
        echo "Starting simple batch consolidation..."
        
        # Get PR number for context
        PR_NUM="${{ github.event.pull_request.number || '' }}"
        
        # Check for batch artifacts (minimal logging)
        BATCH_DIRS_FOUND=false
        if ls review-batch-* 1> /dev/null 2>&1; then
          BATCH_DIRS_FOUND=true
          echo "Found batch directories for consolidation"
        else
          echo "No review-batch-* directories found"
        fi
        
        # Create detailed review by combining all batch results
        echo "# AI Code Review - Detailed Report ${PR_NUM:+for PR #$PR_NUM}" > consolidate_review.md
        echo "" >> consolidate_review.md
        echo "*Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')*" >> consolidate_review.md
        echo "" >> consolidate_review.md
        
        # Check if we have batch artifacts
        if [ "$BATCH_DIRS_FOUND" = true ]; then
          echo "Found batch results, consolidating individual reviews..."
          
          echo "## 📊 Review Summary" >> consolidate_review.md
          echo "" >> consolidate_review.md
          
          # Count total files reviewed
          TOTAL_FILES=0
          BATCH_COUNT=0
          
                     # Process each batch artifact
           for batch_dir in review-batch-*; do
             if [ -d "$batch_dir" ]; then
               BATCH_COUNT=$((BATCH_COUNT + 1))
               echo "Processing batch: $batch_dir"
               
               # Count files in this batch - expect flat structure
               BATCH_FILES=$(find "$batch_dir" -name "*.md" -type f | grep -v summary.json | wc -l)
               TOTAL_FILES=$((TOTAL_FILES + BATCH_FILES))
               echo "- **Batch $BATCH_COUNT:** $BATCH_FILES files reviewed" >> consolidate_review.md
             fi
           done
          
          echo "" >> consolidate_review.md
          echo "### Overall Statistics" >> consolidate_review.md
          echo "- **Total batches:** $BATCH_COUNT" >> consolidate_review.md
          echo "- **Total files reviewed:** $TOTAL_FILES" >> consolidate_review.md
          echo "" >> consolidate_review.md
          
          # Combine all individual file reviews
          echo "## 📝 File Reviews" >> consolidate_review.md
          echo "" >> consolidate_review.md
          
                                # Process each batch directory and accumulate all reviews
            for batch_dir in review-batch-*; do
              if [ -d "$batch_dir" ]; then
                echo "### Batch $batch_dir" >> consolidate_review.md
                echo "" >> consolidate_review.md
                
                # Search for review files in flat structure
                SEARCH_PATH="$batch_dir"
                
                # Process each review file in the batch and add to detailed review
                for review_file in $(find "$SEARCH_PATH" -name "*.md" -type f | grep -v summary.json | sort); do
                  if [ -f "$review_file" ]; then
                    echo "Processing: $review_file"
                    
                    # Extract filename and create a clear heading with robust path reconstruction
                    filename=$(basename "$review_file" .md)
                    
                    # Robust path reconstruction with fallback
                    original_path=""
                    if [[ "$filename" =~ ^[a-zA-Z0-9._-]+$ ]]; then
                      # Try to reconstruct path from sanitized filename
                      temp_path=$(echo "$filename" | sed 's/_/\//g' | sed 's/^\.\///')
                      # Validate the reconstructed path looks reasonable
                      if [[ "$temp_path" =~ ^[a-zA-Z0-9./_-]+$ ]] && [[ "$temp_path" != "$filename" ]]; then
                        original_path="$temp_path"
                      else
                        original_path="$filename (path reconstruction failed)"
                      fi
                    else
                      original_path="$filename (invalid filename format)"
                    fi
                    
                    # Add file heading before the review content
                    echo "### 📄 $original_path" >> consolidate_review.md
                    echo "" >> consolidate_review.md
                    
                    # Add the review content
                    cat "$review_file" >> consolidate_review.md
                    echo "" >> consolidate_review.md
                    echo "---" >> consolidate_review.md
                    echo "" >> consolidate_review.md
                  fi
                done
              fi
            done
          
          # Create AI-generated summary using Gemini CLI
          echo "Generating AI summary of the detailed review..."
          
          # Load summary prompt template
          SUMMARY_TEMPLATE_PATH="$(dirname "$0")/summary-prompt.md"
          if [ ! -f "$SUMMARY_TEMPLATE_PATH" ]; then
            # Try alternative paths
            SUMMARY_TEMPLATE_PATH="./summary-prompt.md"
            if [ ! -f "$SUMMARY_TEMPLATE_PATH" ]; then
              SUMMARY_TEMPLATE_PATH=".github/actions/consolidate-batches/summary-prompt.md"
              if [ ! -f "$SUMMARY_TEMPLATE_PATH" ]; then
                echo "Error: summary-prompt.md not found in any expected location"
                echo "Current directory: $(pwd)"
                echo "Action directory: $(dirname "$0")"
                echo "Tried paths:"
                echo "  - $(dirname "$0")/summary-prompt.md"
                echo "  - ./summary-prompt.md"
                echo "  - .github/actions/consolidate-batches/summary-prompt.md"
                ls -la . || echo "Cannot list current directory"
                exit 1
              fi
            fi
          fi
          SUMMARY_TEMPLATE=$(cat "$SUMMARY_TEMPLATE_PATH")
          
          # Replace placeholder with actual review content
          SUMMARY_PROMPT=$(perl -pe 'BEGIN{undef $/} s/\{\{REVIEW_CONTENT\}\}/do{local $/; open my $fh,"<","consolidate_review.md"; <$fh>}/e' <<<"$SUMMARY_TEMPLATE")

          # Create summary using Gemini CLI
          SUMMARY_CONTENT=$(echo "$SUMMARY_PROMPT" | gemini --model gemini-2.5-pro --prompt - 2>/dev/null || echo "Summary generation failed")
          
          # Create AI-generated summary file
          echo "# AI Code Review - Summary ${PR_NUM:+for PR #$PR_NUM}" > consolidate_summary.md
          echo "" >> consolidate_summary.md
          echo "*Generated on $(date -u '+%Y-%m-%d %H:%M:%S UTC')*" >> consolidate_summary.md
          echo "" >> consolidate_summary.md
          
          echo "## 📊 Review Statistics" >> consolidate_summary.md
          echo "" >> consolidate_summary.md
          echo "- **Total batches:** $BATCH_COUNT" >> consolidate_summary.md
          echo "- **Total files reviewed:** $TOTAL_FILES" >> consolidate_summary.md
          echo "" >> consolidate_summary.md
          
          echo "## 🎯 Executive Summary" >> consolidate_summary.md
          echo "" >> consolidate_summary.md
          echo "$SUMMARY_CONTENT" >> consolidate_summary.md
          echo "" >> consolidate_summary.md
          
          echo "---" >> consolidate_summary.md
          echo "*For detailed review comments and specific recommendations, see the full detailed review.*" >> consolidate_summary.md
          
        else
          echo "No batch results found." >> consolidate_review.md
          echo "No batch results found." >> consolidate_summary.md
        fi
        
        echo "🎉 Batch consolidation complete!"
        echo "📁 Detailed review: consolidate_review.md"
        echo "📋 Summary: consolidate_summary.md"
