name: Prepare Review Manifest Enhanced

on:
  workflow_call:
    inputs:
      exclude_regex:
        type: string
        required: true
      max_files:
        type: string
        required: true
      max_commits:
        type: string
        required: true
      policy_path:
        type: string
        required: true
      control_repo_ref:
        type: string
        required: true
      batch_size:
        type: string
        required: true
      max_parallel_batches:
        type: string
        required: true
    outputs:
      batches:
        description: "JSON array of batches"
        value: ${{ jobs.prepare.outputs.batches }}
      policy_found:
        description: "true/false if a policy file was found"
        value: ${{ jobs.prepare.outputs.policy_found }}
      policy_scope:
        description: "repo/org scope of located policy"
        value: ${{ jobs.prepare.outputs.policy_scope }}
      policy_path_resolved:
        description: "resolved path of policy file"
        value: ${{ jobs.prepare.outputs.policy_path_resolved }}
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      batches: ${{ steps.batch.outputs.batches }}
      policy_found: ${{ steps.policy.outputs.found }}
      policy_scope: ${{ steps.policy.outputs.scope }}
      policy_path_resolved: ${{ steps.policy.outputs.path }}
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref || github.ref }}

      - name: Checkout org .github control repo
        continue-on-error: true
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/.github
          ref: ${{ inputs.control_repo_ref }}
          path: __org_control
          fetch-depth: 1
          token: ${{ secrets.PAT_TOKEN }}

      - name: Locate policy
        id: policy
        uses: softlink-dev/.github/.github/actions/locate-policy@main
        with:
          policy_path: ${{ inputs.policy_path }}

      - name: Generate manifest
        id: manifest
        uses: softlink-dev/.github/.github/actions/generate-manifest@main
        with:
          exclude_regex: ${{ inputs.exclude_regex }}
          max_files: ${{ inputs.max_files }}
          max_commits: ${{ inputs.max_commits }}

      - name: Create batches
        id: batch
        uses: softlink-dev/.github/.github/actions/create-batches@main
        with:
          items_json: ${{ steps.manifest.outputs.items }}
          batch_size: ${{ inputs.batch_size }}
          max_parallel_batches: ${{ inputs.max_parallel_batches }}

      - name: Debug batches output
        shell: bash
        run: |
          echo "🔍 Debug: Batches created successfully"
          echo "Batches output length: $(echo '${{ steps.batch.outputs.batches }}' | wc -c) characters"

      - name: Upload batches artifact
        uses: actions/upload-artifact@v4
        with:
          name: review-batches
          path: ${{ runner.temp }}/batches.json

      - name: Validate batches artifact structure
        shell: bash
        run: |
          echo "🔍 Validating batches artifact structure..."
          
          # Check if batches.json was created
          if [ ! -f "${{ runner.temp }}/batches.json" ]; then
            echo "❌ ERROR: batches.json not found in runner temp directory"
            exit 1
          fi
          
          # Safely check if jq is available
          if ! command -v jq &> /dev/null; then
            echo "⚠️  WARNING: jq not available, skipping JSON validation"
            echo "✅ Batches.json exists (validation skipped)"
            BATCH_COUNT="unknown"
          else
            # Validate JSON structure
            if ! jq -e '.' "${{ runner.temp }}/batches.json" > /dev/null 2>&1; then
              echo "❌ ERROR: batches.json is not valid JSON"
              exit 1
            fi
            
            # Check if it's an array
            if ! jq -e 'type == "array"' "${{ runner.temp }}/batches.json" > /dev/null 2>&1; then
              echo "❌ ERROR: batches.json is not an array"
              exit 1
            fi
            
            # Check array length with error handling
            BATCH_COUNT=$(jq -r 'length' "${{ runner.temp }}/batches.json" 2>/dev/null || echo 'error')
          fi
          
          echo "✅ Found $BATCH_COUNT batches in artifact"
          
          if [ "$BATCH_COUNT" = "0" ]; then
            echo "⚠️  WARNING: No batches found - this may be expected for small PRs"
          elif [ "$BATCH_COUNT" = "error" ]; then
            echo "⚠️  WARNING: Could not determine batch count"
          fi
          
          echo "✅ Batches artifact validation passed"
