name: Test Gemini Modular Review
permissions:
  contents: write
  pull-requests: write
  actions: write
on:
  workflow_dispatch:
    inputs:
      run_prepare:
        description: "Run only prepare module?"
        type: boolean
        default: false

jobs:
  test-prepare:
    if: ${{ github.event.inputs.run_prepare == 'true' }}
    uses: ./.github/workflows/_prepare.yml@main
    with:
      exclude_regex: "(node_modules|dist)/"
      max_files: "5"
      max_commits: "2"
      policy_path: ".github/review/REVIEW_POLICY.md"
      control_repo_ref: "main"
      batch_size: "2"
      max_parallel_batches: "1"
    secrets: inherit

  test-full:
    if: ${{ github.event.inputs.run_prepare != 'true' }}
    uses: ./.github/workflows/gemini-pr-review-v2.yml@main
    with:
      model: gemini-2.5-pro
      max_files: "5"
      max_commits: "2"
      batch_size: "1"
      max_parallel_batches: "1"
      force_review: true
      min_lines_threshold: "1"
    secrets: inherit
